### ISSUE TITLE
Design wireframe

### ISSUE THREAD

**Issue by Draketheb4dass** [CECOFA/BidjePeyim#3]

**Comment by ledanfab** [comment]
![budgetartboard-1](https://user-images.githubusercontent.com/22782294/43683491-c2064efc-9841-11e8-881f-4783477a8ae9.png)
![Uploading budgetArtboard-2.png…]()
![budgetartboard-2-copy](https://user-images.githubusercontent.com/22782294/43683493-c359d8c8-9841-11e8-9cfc-6886b17b374b.png)


HERE THE WIREFRAME
