### ISSUE TITLE
Statistics Activity: How the data should be displayed

### ISSUE THREAD

**Issue by Draketheb4dass** [CECOFA/BidjePeyim#40]
We really need to get to this!

**Comment by pcelande** [comment]
Le fichier nécessaire vient d'être mis en ligne

**Comment by Draketheb4dass** [comment]
comment devront etre affiche ces donnes dans l'appli

**Comment by Draketheb4dass** [comment]
??

**Comment by pcelande** [comment]
Je te montre ce matin au bureau. Tu viens ?

**Comment by Draketheb4dass** [comment]
??
